name: xiloeditor
description: Flet Xiloeditor control
repository: https://github.com/MyGithubAccount/xiloeditor/src/flutter/xiloeditor
version: 0.1.0
homepage: https://github.com/MyGithubAccount/xiloeditor

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.27.6
  flutter_code_editor:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
